# Generated by Django 5.0 on 2023-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
